### ISSUE TITLE
run pytorch version got some error

### ISSUE THREAD

**Issue by ben-wong** [HuiZeng/Grid-Anchor-based-Image-Cropping#1]
Hi, I am running the pytorch version on my local environment(windows 10+pytorch 0.4+python3.6),got following error message:
ModuleNotFoundError: No module named 'roi_align._ext.roi_align._roi_align'

I found there is an .so file that windows can't read.
How can I solve this error?
Looking forward to hearing from you soon.

**Comment by HuiZeng** [comment]
Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions.  I have not tried that so I cannot provide more specific suggestions on your question.

**Comment by lld533** [comment]
> ndows 10+pytorch 0.4+python3.6),got following error message:
> ModuleNotFoundError: No module named 'roi_align._ext.roi_align._roi_align'
> I found there is an .so file that windows can't read.
> How can I solve this error?
> Looking forward to hearing from you soon.

.SO are dynamic libraries on Linux. Please re-compile the source code on Windows and accordingly generate your own .DLL files.

**Comment by WujiangXu** [comment]
> Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions. I have not tried that so I cannot provide more specific suggestions on your question.

May I ask you the version of python，pytorch，torchvision use in this code？

**Comment by HuiZeng** [comment]
> > Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions. I have not tried that so I cannot provide more specific suggestions on your question.
> 
> May I ask you the version of python，pytorch，torchvision use in this code？

Hi, I used python 2.7, and pytorch 0.4.1.

**Comment by WujiangXu** [comment]
> > > Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions. I have not tried that so I cannot provide more specific suggestions on your question.
> > 
> > 
> > May I ask you the version of python，pytorch，torchvision use in this code？
> 
> Hi, I used python 2.7, and pytorch 0.4.1.

Hi，Is it all I need to configure these environments.Then I can run the demo_eval.py successfully.

**Comment by HuiZeng** [comment]
> > > > Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions. I have not tried that so I cannot provide more specific suggestions on your question.
> > > 
> > > 
> > > May I ask you the version of python，pytorch，torchvision use in this code？
> > 
> > 
> > Hi, I used python 2.7, and pytorch 0.4.1.
> 
> Hi，Is it all I need to configure these environments.Then I can run the demo_eval.py successfully.

Almost. The other required libraries such as cv2 are easy to install.

**Comment by cupcakefromchina** [comment]
> > > > > Hi, I have only tested the pytorch code on ubuntu. On windows, you may need to re-compile the source code of roi_align and rod_align functions. I have not tried that so I cannot provide more specific suggestions on your question.
> > > > 
> > > > 
> > > > May I ask you the version of python，pytorch，torchvision use in this code？
> > > 
> > > 
> > > Hi, I used python 2.7, and pytorch 0.4.1.
> > 
> > 
> > Hi，Is it all I need to configure these environments.Then I can run the demo_eval.py successfully.
> 
> Almost. The other required libraries such as cv2 are easy to install.

Sorry to interrupt you again.
I want to know what I need to change to the code.
After I change the path of dataset_root and net_path.
I run the demo_eval.py.But I failed to receive the information on the cv2.imwrite.
` File "demo_eval.py", line 100, in <module>
    test()
  File "demo_eval.py", line 91, in test
    cv2.imwrite('/mypath'+imgname[:-4]+'crop_'+str(id+1)+imgname[-4:],top_crop[:,:,(2, 1, 0)])
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:662: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'
`
