### ISSUE TITLE
How to specific the resolution and the cropping ratio in python code? 

### ISSUE THREAD

**Issue by hamhochoi** [HuiZeng/Grid-Anchor-based-Image-Cropping#10]
I installed the python version code of this project. In README.md file, there is "Notification: the trained model naturally supports generating crops having fixed aspect ratios or resolutions. This function can be supported when necessary in the future.".
So how can I specific the ratio and resolutions of the output?

**Comment by HuiZeng** [comment]
For generating crops having fixed aspect ratio, you need to change the generate_crop function to generate a set of candidate crops having fixed aspect ratio. You can refer to the implementations in testGAIC_qualitative_customer.m.

**Comment by hamhochoi** [comment]
Where is the generate_crop function? Do you mean generate_bboxes() function in croppingDataset.py?

**Comment by HuiZeng** [comment]
Yes.

**Comment by HuiZeng** [comment]
Another way is to increase the bin number and change the aspect ratio constraint to generate crops having aspect ration in a certain range.

**Comment by hamhochoi** [comment]
Thank you! I will try both way

**Comment by hamhochoi** [comment]
It's worked, thank you so much!

**Comment by ryanaleksander** [comment]
I'm very sorry but I still don't understand how to accomplish this. Would you mind telling me how you did it @hamhochoi ?

**Comment by hamhochoi** [comment]
You can change ratio constraint in generate_bboxes() to get output images have ratio close with the ratio you want. Example, if you want the ratio to be 4:3 (~1.333) then you should modify the lower and upper bound to close 1.3. Also, you man want to change the value of bins in the code to get the result. To better understand why do that, read the author's paper! 

![Screenshot from 2019-07-15 16-27-22](https://user-images.githubusercontent.com/16822227/61206799-a673ae00-a71d-11e9-8eb0-0f5cbda665fc.png)
