### ISSUE TITLE
What is you requirements for pytorch project?

### ISSUE THREAD

**Issue by andriyrizhiy** [HuiZeng/Grid-Anchor-based-Image-Cropping#12]
I don't run you pytorch project becouse i have an error 

> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by HuiZeng** [comment]
This error can be solved by using pytorch version 0.4.1. The latest pytorch
does not support ffi extension anymore.

andriyrizhiy <notifications@github.com> 于 2019年8月13日周二 下午11:09写道：
