### ISSUE TITLE
What role does testmodel play?

### ISSUE THREAD

**Issue by WujiangXu** [HuiZeng/Grid-Anchor-based-Image-Cropping#16]
Maybe i meet the error.But I don't know what cause that.I run the testmodel.m and print the highest score of each photo.In the  first 1-5 epoch,the highest score normally is 3-5.But in the later epoch,the highest score just 1. 
  I use the same dataset about the train and the test.But the testmodel.m can't give me the five point in the later epoch.It confused me.
  Thank u for u reply.

**Comment by HuiZeng** [comment]
Are the accuracies and SRCC normal in the later epochs? I did not print the predicted scores since both metrices are based on the ranking orders rather than the absolute values.

**Comment by WujiangXu** [comment]
The value of SRCC in early epoch is 0.7-0.8,in the later epoch is 0.92.What does it mean?
And there are another question.I use the resnet50 to train my dataset.The result of that are not better than the VGG16.

**Comment by HuiZeng** [comment]
0.92 seems too high for the SRCC. 
In my experiments, the resnet50 also obtained worse performance than the vgg16.
The details of these two aspects can be found in the paper.

**Comment by WujiangXu** [comment]
> 0.92 seems too high for the SRCC.
> In my experiments, the resnet50 also obtained worse performance than the vgg16.
> The details of these two aspects can be found in the paper.

Thank you for your reply.I found that our database may have some errors.
