### ISSUE TITLE
Can you provide the training code in pytorch?

### ISSUE THREAD

**Issue by GaoSandy** [HuiZeng/Grid-Anchor-based-Image-Cropping#2]
Hello , you've done a good job!  But there are no training details in pytorch code. So could you mind  provide it? thanks a lot!

**Comment by HuiZeng** [comment]
> Hello , you've done a good job! But there are no training details in pytorch code. So could you mind provide it? thanks a lot!

Hi, sorry for the late reply. I do have the training code, but currently do not have the plan to release it. You can find the training details in the matlab training code. 
The whole pytroch code will be released with our journal version paper, perhaps in several months.
