### ISSUE TITLE
When I run the code for evulation

### ISSUE THREAD

**Issue by WujiangXu** [HuiZeng/Grid-Anchor-based-Image-Cropping#3]
Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m  for evulation,I saw these error information.

`Undefined function or variable 'dagnn.RoiAlign'.

Error in dagnn.DagNN.loadobj (line 26)
    block = constr() ;

Error in testGAIC_qualitative_customer (line 19)
net = dagnn.DagNN.loadobj(netStruct.net) ;

Error in run (line 91)
evalin('caller', strcat(script, ';'));
`

**Comment by HuiZeng** [comment]
> Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m for evulation,I saw these error information.
> 
> `Undefined function or variable 'dagnn.RoiAlign'.
> 
> Error in dagnn.DagNN.loadobj (line 26)
> block = constr() ;
> 
> Error in testGAIC_qualitative_customer (line 19)
> net = dagnn.DagNN.loadobj(netStruct.net) ;
> 
> Error in run (line 91)
> evalin('caller', strcat(script, ';'));
> `

Try first run line 4-6 in RunExperiment.m to add paths into the environment.

**Comment by WujiangXu** [comment]
> > Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m for evulation,I saw these error information.
> > `Undefined function or variable 'dagnn.RoiAlign'.
> > Error in dagnn.DagNN.loadobj (line 26)
> > block = constr() ;
> > Error in testGAIC_qualitative_customer (line 19)
> > net = dagnn.DagNN.loadobj(netStruct.net) ;
> > Error in run (line 91)
> > evalin('caller', strcat(script, ';'));
> > `
> 
> Try first run line 4-6 in RunExperiment.m to add paths into the environment.

Thank you for you reply.But it doesn't work out.I have changed the code as this.
`
function testGAIC_qualitative()

cd /(mypath)/matconvnet-1.0-beta25; 
addpath(genpath('tools'));
addpath(genpath('src'));
run /(mypath)/matconvnet-1.0-beta25/matlab/vl_setupnn.m;
`

**Comment by WujiangXu** [comment]
Hello.When I run the RunExperiment.m，it comes to more errors than this.I have set the GAIC in the dataset.But it looks useless.

`train: epoch 01:   1/1000:dataset/GAIC/images/train/211958.jpg: error 'imread_libjpeg: unable to open dataset/GAIC/images/train/211958.jpg'
Error using imresize
Expected input number 1, A, to be nonempty.

Error in imresize>parsePreMethodArgs (line 345)
validateattributes(A, {'single', ...

Error in imresize>parseInputs (line 260)
[params.A, params.map, params.scale, params.output_size] = ...

Error in imresize (line 146)
params = parseInputs(args{:});

Error in trainModel>getBatch_rois (line 89)
    imre = imresize(imo{i},opts.minScale/min([x1,x2]),'bilinear');

Error in trainModel>@(i,b)getBatch_rois(opts,i,b) (line 75)
[net, info] = cnn_train_dag(net, imdb, @(i,b) getBatch_rois(opts,i,b),...

Error in cnn_train_dag>processEpoch (line 237)
    inputs = params.getBatch(params.imdb, batch) ;

Error in cnn_train_dag (line 105)
    [net, state] = processEpoch(net, state, params, 'train') ;

Error in trainModel (line 75)
[net, info] = cnn_train_dag(net, imdb, @(i,b) getBatch_rois(opts,i,b),...

Error in RunExperiment (line 20)
trainModel('database',database,'model',model,'downsample',downsample,'RoIRoD',RoIRoD,...

Error in run (line 91)
evalin('caller', strcat(script, ';'));
`

**Comment by HuiZeng** [comment]
> Hello.When I run the RunExperiment.m，it comes to more errors than this.I have set the GAIC in the dataset.But it looks useless.
> 
> `train: epoch 01: 1/1000:dataset/GAIC/images/train/211958.jpg: error 'imread_libjpeg: unable to open dataset/GAIC/images/train/211958.jpg'
> 

Can you find the image in the corresponding folder? If yes, then the problem may be caused by imread_libjpeg.

**Comment by WujiangXu** [comment]
> > Hello.When I run the RunExperiment.m，it comes to more errors than this.I have set the GAIC in the dataset.But it looks useless.
> > `train: epoch 01: 1/1000:dataset/GAIC/images/train/211958.jpg: error 'imread_libjpeg: unable to open dataset/GAIC/images/train/211958.jpg'
> 
> Can you find the image in the corresponding folder? If yes, then the problem may be caused by imread_libjpeg.

I changed the setup_database_GAIC.m.I changed the train_img_dir and the test_img_dir.But it doesn't seem to change the path of the picture.

**Comment by WujiangXu** [comment]
> > Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m for evulation,I saw these error information.
> > `Undefined function or variable 'dagnn.RoiAlign'.
> > Error in dagnn.DagNN.loadobj (line 26)
> > block = constr() ;
> > Error in testGAIC_qualitative_customer (line 19)
> > net = dagnn.DagNN.loadobj(netStruct.net) ;
> > Error in run (line 91)
> > evalin('caller', strcat(script, ';'));
> > `
> 
> Try first run line 4-6 in RunExperiment.m to add paths into the environment.

I add the line 4-6  in RunExperiment.m.But now it comes to new errors.Like this.
`Error using dagnn.Layer/load (line 200)
No property `normalise` for a layer of type `dagnn.RegressionLoss`.

Error in dagnn.DagNN.loadobj (line 27)
    block.load(struct(s.layers(l).block)) ;

Error in testGAIC_qualitative (line 20)
net = dagnn.DagNN.loadobj(netStruct.net) ;

Error in run (line 91)
evalin('caller', strcat(script, ';'));
`

**Comment by HuiZeng** [comment]
> > > Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m for evulation,I saw these error information.
> > > `Undefined function or variable 'dagnn.RoiAlign'. Error in dagnn.DagNN.loadobj (line 26) block = constr() ; Error in testGAIC_qualitative_customer (line 19) net = dagnn.DagNN.loadobj(netStruct.net) ; Error in run (line 91) evalin('caller', strcat(script, ';')); `
> > 
> > 
> > Try first run line 4-6 in RunExperiment.m to add paths into the environment.
> 
> I add the line 4-6 in RunExperiment.m.But now it comes to new errors.Like this.
> `Error using dagnn.Layer/load (line 200) No property `normalise`for a layer of type`dagnn.RegressionLoss`.
> 
> Error in dagnn.DagNN.loadobj (line 27)
> block.load(struct(s.layers(l).block)) ;
> 
> Error in testGAIC_qualitative (line 20)
> net = dagnn.DagNN.loadobj(netStruct.net) ;
> 
> Error in run (line 91)
> evalin('caller', strcat(script, ';'));
> `

I have not encountered these problems in my devices.  
I used matconvnet-1.0-beta24, but this should not be the reason.

**Comment by WujiangXu** [comment]
> > > > Before I run this code,I setup and test the matconvent successfully.But I run the testGAIC_qualitative_customer.m for evulation,I saw these error information.
> > > > `Undefined function or variable 'dagnn.RoiAlign'. Error in dagnn.DagNN.loadobj (line 26) block = constr() ; Error in testGAIC_qualitative_customer (line 19) net = dagnn.DagNN.loadobj(netStruct.net) ; Error in run (line 91) evalin('caller', strcat(script, ';')); `
> > > 
> > > 
> > > Try first run line 4-6 in RunExperiment.m to add paths into the environment.
> > 
> > 
> > I add the line 4-6 in RunExperiment.m.But now it comes to new errors.Like this.
> > `Error using dagnn.Layer/load (line 200) No property `normalise`for a layer of type`dagnn.RegressionLoss`.
> > Error in dagnn.DagNN.loadobj (line 27)
> > block.load(struct(s.layers(l).block)) ;
> > Error in testGAIC_qualitative (line 20)
> > net = dagnn.DagNN.loadobj(netStruct.net) ;
> > Error in run (line 91)
> > evalin('caller', strcat(script, ';'));
> > `
> 
> I have not encountered these problems in my devices.
> I used matconvnet-1.0-beta24, but this should not be the reason.

Oh,thank you for your help.I will try to use beta24 later.

**Comment by WujiangXu** [comment]
Whether I just need to run the RunExperiment.m well,I can get the crop result of the test gragh.

**Comment by WujiangXu** [comment]
Oh，I use the fprintf to find this code that cause the error.But I don't know it means.
`net = dagnn.DagNN.loadobj(netStruct.net) ;`

**Comment by WujiangXu** [comment]
I solve the problem.I guess may the version of the model not match with my code.I use the beta24 and matlab2018a.
If other people meet the problem,you can use the RunExperiment.m to train the model which is matching with your code.Then it will be no error.

**Comment by HuiZeng** [comment]
> I solve the problem.I guess may the version of the model not match with my code.I use the beta24 and matlab2018a.
> If other people meet the problem,you can use the RunExperiment.m to train the model which is matching with your code.Then it will be no error.

Thanks for your information!

**Comment by KOEI1997** [comment]
你好，我也遇到了和你一样的问题，请问你最后是怎么解决的呢？我使用的matlab版本是R2016a

**Comment by WujiangXu** [comment]
> 你好，我也遇到了和你一样的问题，请问你最后是怎么解决的呢？我使用的matlab版本是R2016a

使用作者的训练代码训练你的模型，它会生成新的网络，名字形式如net-epoch-40.net，然后使用这个新的网络可以进行裁剪的测试。

**Comment by KOEI1997** [comment]
> > 你好，我也遇到了和你一样的问题，请问你最后是怎么解决的呢？我使用的matlab版本是R2016a
> 
> 使用作者的训练代码训练你的模型，它会生成新的网络，名字形式如net-epoch-40.net，然后使用这个新的网络可以进行裁剪的测试。

我明白你的意思了！ 但是运行trainModel时会出现这个错误怎么办呢？一直尝试还没有找到解决的办法T.T

train: epoch 01:   1/1000:dataset/GAIC/images/train/398241.jpg: error 'gdi+: InvalidParameter (or image file does not exist)'
错误使用 imresize
需要的 第 1 个输入, A, 应为 非空。

**Comment by WujiangXu** [comment]
> > > 你好，我也遇到了和你一样的问题，请问你最后是怎么解决的呢？我使用的matlab版本是R2016a
> > 
> > 
> > 使用作者的训练代码训练你的模型，它会生成新的网络，名字形式如net-epoch-40.net，然后使用这个新的网络可以进行裁剪的测试。
> 
> 我明白你的意思了！ 但是运行trainModel时会出现这个错误怎么办呢？一直尝试还没有找到解决的办法T.T
> 
> train: epoch 01: 1/1000:dataset/GAIC/images/train/398241.jpg: error 'gdi+: InvalidParameter (or image file does not exist)'
> 错误使用 imresize
> 需要的 第 1 个输入, A, 应为 非空。

改变那个.m文件 来修改图片路径 setup_database_GAIC.m

**Comment by KOEI1997** [comment]
> > > > 你好，我也遇到了和你一样的问题，请问你最后是怎么解决的呢？我使用的matlab版本是R2016a
> > > 
> > > 
> > > 使用作者的训练代码训练你的模型，它会生成新的网络，名字形式如net-epoch-40.net，然后使用这个新的网络可以进行裁剪的测试。
> > 
> > 
> > 我明白你的意思了！ 但是运行trainModel时会出现这个错误怎么办呢？一直尝试还没有找到解决的办法T.T
> > train: epoch 01: 1/1000:dataset/GAIC/images/train/398241.jpg: error 'gdi+: InvalidParameter (or image file does not exist)'
> > 错误使用 imresize
> > 需要的 第 1 个输入, A, 应为 非空。
> 
> 改变那个.m文件 来修改图片路径 setup_database_GAIC.m

图片路径是正确的诶，但还是出现这样的错误

**Comment by cherryolg** [comment]
`错误使用 dagnn.Layer/load (line 200)
No property `normalise` for a layer of type `dagnn.RegressionLoss`.

出错 dagnn.DagNN.loadobj (line 27)
    block.load(struct(s.layers(l).block)) ;

出错 testGAIC_qualitative_customer (line 20)
net = dagnn.DagNN.loadobj(netStruct.net) ;`
你好，我想要输入图片，然后生成裁剪的测试结果。在运行testGAIC_qualitative_customer.m和testGAIC_qualitative.m都遇到上述问题了。请问你是怎么解决的呢？我的matlab版本是2018b，matconvnet-1.0-beta25。只能重新训练才能测试结果吗？不能直接使用作者提供的epoch37的训练模型吗？期待你的解答
