### ISSUE TITLE
Run Pytorch version error get some error

### ISSUE THREAD

**Issue by TPLian5755** [HuiZeng/Grid-Anchor-based-Image-Cropping#5]
when I run the demo_eval.py on ubuntu,I met an error:
ImportError:My_path/pytorch_cropping_evaluation/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: PyInt_FromLong

how can I solve the problem
 I use python3.6   pytorch0.4.1

**Comment by HuiZeng** [comment]
I used python 2.7 and pytorch 0.4.1。Other version may have problem when building the source code of roi_align.-------- 原始邮件 --------主题：[HuiZeng/Grid-Anchor-based-Image-Cropping] Run Pytorch version error get some error (#5)发件人：maomaochong5755 收件人：HuiZeng/Grid-Anchor-based-Image-Cropping 抄送：Subscribed when I run the demo_eval.py on ubuntu,I met an error:
ImportError:My_path/pytorch_cropping_evaluation/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: PyInt_FromLong
how can I solve the problem
I use python3.6   pytorch0.4.1

**Comment by TPLian5755** [comment]
请问数据库中有些图片个别裁剪方式的评分是-2，这代表什么含义？不是说所有得分都是介于1-5之间吗？

**Comment by HuiZeng** [comment]
Please refer to this issue #8

**Comment by TPLian5755** [comment]
请问你在训练的时候用了哪些数据增强的方式啊？

**Comment by HuiZeng** [comment]
这个版本几乎没用什么数据增广，所有细节都在代码里面了。
