### ISSUE TITLE
Is there a url to download dataset GAICD

### ISSUE THREAD

**Issue by MiracleHW** [HuiZeng/Grid-Anchor-based-Image-Cropping#6]
I not find the url to download the dataset GAICD( Grid Anchor
based Image Cropping Database)，is there a way to down the dataset？

**Comment by HuiZeng** [comment]
Interesting...
Can't you see the super link of the dataset in the code page?
![image](https://user-images.githubusercontent.com/12780780/60657565-24b19400-9e84-11e9-97f2-74e2b864b89d.png)

**Comment by MiracleHW** [comment]
> Interesting...
> Can't you see the super link of the dataset in the code page?
> ![image](https://user-images.githubusercontent.com/12780780/60657565-24b19400-9e84-11e9-97f2-74e2b864b89d.png)

Thanks for your reminding , im not I notice that，and thanks for your data

**Comment by HuiZeng** [comment]
> > Interesting...
> > Can't you see the super link of the dataset in the code page?
> > ![image](https://user-images.githubusercontent.com/12780780/60657565-24b19400-9e84-11e9-97f2-74e2b864b89d.png)
> 
> Thanks for your reminding , im not I notice that，and thanks for your data

You are welcome and thanks for your interest.
