### ISSUE TITLE
pytorch  problem:   /_roi_align.so: undefined symbol: PyInt_FromLong

### ISSUE THREAD

**Issue by ccczhixian** [HuiZeng/Grid-Anchor-based-Image-Cropping#7]
Hi , when I run the demo_eval.py on linux, there had  an error:
ImportError :/pytorch_cropping_evaluation/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: PyInt_FromLong

could you please tell me how can I solve the problem?

**Comment by HuiZeng** [comment]
> Hi , when I run the demo_eval.py on linux, there had an error:
> ImportError :/pytorch_cropping_evaluation/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: PyInt_FromLong
> 
> could you please tell me how can I solve the problem?

You need to compile the source code of roi_align in your environment and generate the .so file. 
Please see this issue: https://github.com/HuiZeng/Grid-Anchor-based-Image-Cropping/issues/1

**Comment by ccczhixian** [comment]
sm_52在哪里定义

**Comment by HuiZeng** [comment]
> sm_52在哪里定义

这个是什么？

**Comment by ccczhixian** [comment]
![image](https://user-images.githubusercontent.com/24219700/60708833-87b53080-9f41-11e9-92be-8c34637eaebc.png)

**Comment by ccczhixian** [comment]
我编译的时候报错
![image](https://user-images.githubusercontent.com/24219700/60708915-bf23dd00-9f41-11e9-89ad-952e989a7922.png)

**Comment by HuiZeng** [comment]
这个参数好像和cuda版本有关。

**Comment by lld533** [comment]
> 我编译的时候报错

我觉得和CUDA版本以及使用的显卡都有关系。
可以联系一下工作站/服务器的管理员，或者找amax的销售也可以，确认一下当前的cuda版本以及所使用的显卡型号，根据显卡的型号，从下面的链接里面找出对应的gpu architecture的架构号码，修改sm_52。通常1080或者1080ti都是sm_60或以上，2080ti等的sm号码更大一些，sm_52适应于比较早的显卡结构。
[https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/](url)

**Comment by TPLian5755** [comment]
怎么在Ubuntu下重新编译roi_align源码生成.so文件啊？

**Comment by HuiZeng** [comment]
> 怎么在Ubuntu下重新编译roi_align源码生成.so文件啊？

相应的文件夹下给了make.sh文件，不过好像对pytorch的版本有一定的要求，pytorch0.4.1可以，太新的版本比如1.0之后好像改了一些底层的东西，就会报错。
