### ISSUE TITLE
GAIC Score of -2.00

### ISSUE THREAD

**Issue by ycvision** [HuiZeng/Grid-Anchor-based-Image-Cropping#8]
Hello Hui, in every txt file in the dataset you provided, there are always some crops that have scores of -2.00. Is that a bug in the dataset collection procedure?

**Comment by HuiZeng** [comment]
Hi, -2 means that crop violates one of the three constraints in our formulation, that crop is not annotated. You should directly skip such crops.-------- 原始邮件 --------主题：[HuiZeng/Grid-Anchor-based-Image-Cropping] GAIC Score of -2.00 (#8)发件人：Yang Cheng 收件人：HuiZeng/Grid-Anchor-based-Image-Cropping 抄送：Subscribed Hello Hui, in every txt file in the dataset you provided, there are always some crops that have scores of -2.00. Is that a bug in the dataset collection procedure?
